# Generated by Django 6.0.7 on 2026-08-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("project_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("project_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectShare",
            fields=[
                (
                    "project_share_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "permission_level",
                    models.CharField(
                        choices=[
                            ("VIEWER", "Viewer"),
                            ("EDITOR", "Editor"),
                            ("ADMIN", "Admin"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
