# Generated by Django 6.0.7 on 2026-08-11 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0003_2_11"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationSubscription",
            fields=[
                (
                    "stripe_subscription",
                    models.OneToOneField(
                        db_column="stripe_subscription_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="djstripe.subscription",
                        to_field="id",
                    ),
                ),
                (
                    "org",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
    ]
